config/routes.rb
Rails.application.routes.draw do
  root 'pages#home' 
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new' 
  resources :users, except: [:new] 
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories 
    has_many :categories, through: :article_categories 

     validates :title, presence: true, length:{minimum: 6, maximum: 100}
     validates :description, presence: true, length: {minimum: 100} 
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :article
    belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true,length: { minimum: 4, maximum: 16 }
    validates_uniqueness_of :name 
    has_many :article_categories
    has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
  before_validation {self.email = email.downcase}
  has_many :articles, dependent: :destroy
  validates :username, presence: true,
                        uniqueness: { case_sensitive: false }, 
                        length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
                    uniqueness: { case_sensitive: false }, 
                    length: { maximum: 105}, 
                    format: { with: VALID_EMAIL_REGEX }
 has_secure_password
  end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    helper_method :current_user, :logged_in?
     def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
        #meminization istead of quaring the database a bunch of time meminization will make sure that are returning the session object instead of quarying the database
     end 

     def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:alert]="You must be (LOGGED IN!) to preform that task."
            redirect_to login_path
         end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article_id, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_current_user, only: [:edit, :update, :destroy]
  def show 
  end 

  def index
   @articles = Article.paginate(page: params[:page], per_page: 5)
  end 

   def new 
    @article = Article.new
   end

   def edit
   end 

   def create
     @article = Article.new(article_params)
     @article.user = current_user
     if @article.save
      flash[:notice] = "Article was created sucseefully."
     redirect_to @article
    else  
      render 'new'
   end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was edited sucseefully."
     redirect_to @article
    else  
      render 'edit'
   end
  end
  
  def destroy
    @article.destroy
    redirect_to articles_path
  end 

   private

   def find_article_id 
    @article = Article.find(params[:id]) 
    end 

   def article_params 
    params.require(:article).permit(:title, :description, category_ids:[])
   end
   
   def require_current_user
      if current_user != @article.user && !current_user.admin?
         flash[:alert]= "You can only tinker with your own entries "
         redirect_to @article
      end
   end

end 

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    before_action :require_admin, except: [:index, :show]

    def new
        @category = Category.new
    end
    
    def create
        @category = Category.new(cat_params )
        if @category.save 
            flash[:notice] = "This category was successfully created"
            redirect_to @category
        else
            render 'new'
        end
    end

    def show
        @category = Category.find(params[:id])
        @articles = @category.articles.paginate(page: params[:page], per_page: 5)
    end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
         if @category.update(cat_params)
         flash[:notice] = "Category name updated successfully"
         redirect_to @category
         else
            flash[:alert] = "That action is not valid name must be longer then 3 but less then 17 char"
         render 'edit'
        end
    end
        def index

            @categories = Category.paginate(page: params[:page], per_page: 5)
        end

    private

    def cat_params
        params.require(:category).permit(:name)
    end 

    def require_admin
        if !(logged_in? && current_user.admin?)
        flash[:alert] = "Only admins can preform this task"
        redirect_to categories_path
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home 
        redirect_to  articles_path if logged_in?
    end 

    def about
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new 
    end

    def create 
        
        user = User.find_by(username: params[:session][:username])

        if user  && user.authenticate(params[:session][:password])
            #session instance method
            session[:user_id] = user.id
          
            # https://guides.rubyonrails.org/action_controller_overview.html section 5
            flash[:notice] = "Log in was Successful!" 
            redirect_to user
        else
            flash.now[:alert] = "Your Username or Password was incorrect please try again"
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil 
        flash[:notice]  = "You have successfully logged out!"
       redirect_to root_path
    end 

end


#use flash[:notice] for redirects as the message shows up after the redirect has taken place  flash.now[:alert]] on renders happens before 

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit,:update, :destroy]
    before_action :require_user, only: [:show, :index]
    before_action :require_current_user, only: [:edit, :update, :destroy]

    def show 
  
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
    end 

    def index
    @users = User.paginate(page: params[:page], per_page: 5)
    end

    def new
        @user = User.new
    end

    def edit
   
    end 

    def update
       
        if @user.update(user_params)
            flash[:notice] = "#{@user.username} was edited sucseefully."
            redirect_to @user
          else  
            render 'edit'
         end
    end

    def create
    @user = User.new(user_params )
    if @user.save 
        session[:user_id] = @user.id
        flash[:notice] = "Welcome to TriBlog #{@user.username}, your account has successfully been created!"
        redirect_to articles_path
    else 
        render 'new'
         end 
    end

    def destroy 
         @user.destroy
         session[:user_id] = nil if @user == current_user
         flash[:notice] = "Sorry to see you go your account and all associated data has been deleted"
         redirect_to root_path
    end

    private 

    def user_params 
         params.require(:user).permit(:username, :email, :password)
    end 
    def set_user
         @user = User.find(params[:id])  
    end

    def require_current_user
        if current_user != @user && !current_user.admin?
        flash[:alert] = "You can only tinker with your own profile?"
            redirect_to @user
        end
     end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = {size: 80})
        email_address = user.email.downcase
        hash = Digest::MD5.hexdigest(email_address)
        size = options[:size]
        gravatar_url ="https://www.gravatar.com/avatar/#{hash}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: " rounded shadow mx-auto d-block")
    end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
    <div class="container">
                <% @articles.each do |a|%>
                <div class="row justify-content-md-center">
                    <div class="col-8 mt-4">
                        <div class="card text-center shadow mb-5 bg-white rounded">
                        <div class="card-header font-italic">
                        <% if a.user%>
                         by <%=link_to  a.user.username, user_path(a.user) %>
                         <%end%>
                        <% if a.categories.any? %>
                             <div class="mt-2"><%=render a.categories%></div>
                        <%end%>
                    </div>
                        <div class="card-body">
                            <h5 class="card-title"><%= link_to a.title, article_path(a), class: "text-success" %></td></h5>
                            <p class="card-text"><%= truncate(a.description, length: 50)%></td></p>
                            <%= link_to "View", article_path(a), class: "btn btn-success"%>   
                            <% if logged_in?  &&  (a.user == current_user || current_user.admin?)%>
                                 <%= link_to "Edit", edit_article_path(a), class: "btn btn-warning" %>
                                 <%= link_to "Delete", article_path(a), class: "btn btn-danger", method: :delete, data: {confirm: "Are you sure?"} %>
                            <%end%>
                        </div>
                        <div class="card-footer text-muted">
                             <small>Created <%= time_ago_in_words(a.created_at) %> ago, 
                             edited <%= time_ago_in_words(a.updated_at) %> ago</small>
                        </div>
                </div>
        </div>
    </div>
    <%end%>
    </div>

app/views/articles/_form.html.erb
<div class="container ">
    <div class="row justify-content-center ">
        <div class="col-10">
         <%=render 'shared/error', obj: @article%>
            <div class="card text-center shadow mb-3 bg-white rounded">
                 <div class="card-header font-italic">
                  <%# by <%= @article.user.username if @article.user%> 
                  </div>  
                <%= form_with( model: @article, class: "shadow p-5 mb-3 bg-danger ", local: true) do |f|%>
                  
                <div class="form-group row">
                        <%=f.label :title, class: "col-2 col-form-label text-light"%>
                    <div class="col-10">
                        <%=f.text_field :title, class: "form-control", placeholder: "Title of article"  %>
                    </div>
                </div>

                <div class="form-group row">
                        <%=f.label :description, class:"col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= f.text_area :description, row: 10, class: "form-control shadow rounded", placeholder: "Description of article"   %>
                    </div>
                </div>
                
               <div class="form-group row">
                         <%= f.label :category, class: "col-2 col-form-label text-light" %>
                     <div class="col-10"> 
                         <%= f.collection_select(:category_ids, Category.all, :id, :name,
                         {prompt: "Make your Article easier to find by adding Categories!(can be empty)."}, { multiple: true, size: 3, class: "custom-select shadow rounded" }) %>
                     </div>
                </div>


                <div class="form-group row justify-content-center ">
                    <%=f.submit class: "btn btn-outline-light btn-lg"%>
                </div>
                <% end %>
                </div>
        </div> 
                <div class="mb-3">
                     <%= link_to ' [Cancel and Return to Main page]', articles_path, class: "text-danger" %>
                </div>
               
    </div>    
</div>

app/views/articles/edit.html.erb
    <h1 class = "text-center mt-4 font-weight-bold">Edit Article</h1>
        <%=render 'form'%>
      

app/views/articles/index.html.erb
    <h1 class = "text-center mt-4">All Articles</h1>
      <div class="flickr_pagination">
         <%= will_paginate @articles, :container => false %>
      </div>
      <%=render 'article' %>
      <div class="flickr_pagination mb-4">
        <div class="page_info mb-2">
            <%= page_entries_info @articles %>
        </div>
         <%= will_paginate @articles, :container => false %>
      </div>

app/views/articles/new.html.erb
    <h1 class = "text-center mt-5 font-weight-bold ">Create New Article</h1>
        <%=render 'form'%>

app/views/articles/show.html.erb
<h2 class = "text-center mt-4"><%=@article.title %></h2>
<div class="container">
     <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
            <div class="card text-center shadow mb-5 bg-white rounded">
                 <div class="card-header font-italic">
                     by <%= @article.user.username if @article.user%>
                     <%=link_to gravatar_for(@article.user), user_path(@article.user) %>
                     <% if @article.categories.any? %>
                          <div class="mt-2"><%=render @article.categories%></div>
                     <%end%>
                 </div>

                <div class="card-body">
                     <div class="card-text text-left"><%= simple_format(@article.description)%></td></div>
                     <%if logged_in? && @article.user == current_user || current_user.admin? %>  
                         <%= link_to "Edit", edit_article_path(@article), class: "btn btn-warning" %>
                         <%= link_to "Delete", article_path(@article), class: "btn btn-danger", method: :delete, data: {confirm: "Are you sure?"} %>
                     <%end%>
                </div>
                
                <div class="card-footer text-muted">
                     <%= link_to ' [Cancel and Return to Main page]', articles_path, class: "text-danger" %><br>
                     <small>Created <%= time_ago_in_words(@article.created_at) %> ago, 
                     edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/categories/_category.html.erb
<%=link_to category.name, category_path(category), class: "badge bage-pill badge-info mr-1"%> 

app/views/categories/_form.html.erb
  <%# <%= render 'shared/errors', obj: @category %> 
      <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :name, "Category name", class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
     <% end %> 

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Edit category name</h1>
<div class="row justify-content-center">
    <div class="col-10">
      <%= render 'form' %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
      <%= link_to '[ Cancel and return to categories listing ]', categories_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories</h1>

<div class="flickr_pagination">
  <%= will_paginate @categories, :container => false %>
</div>

<div class="container">
  <% @categories.each do |category| %>
    <div class="row justify-content-md-center">
      <div class="col-4 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body">
            <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success" %></h5>
             <p class="card-text"><%= pluralize(category.articles.count, "article") %></td></p>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(category.created_at) %> ago, 
            edited <%= time_ago_in_words(category.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flickr_pagination mb-4">
  <%= will_paginate @categories, :container => false %>
</div> 

app/views/categories/new.html.erb
<h1 class = "text-center mt-5 font-weight-bold ">Create New Category</h1>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'form' %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
      <%= link_to '[ Cancel and return to categories listing ]', categories_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<h1 class = "text-center mt-4  ">Category:<%=@category.name %></h1>
<div class= "text-center mt-4">
     <%if logged_in? && current_user.admin? %>
     <%= link_to "Edit a Category", edit_category_path(@category), class: "btn btn-warning" %>
<%end%>
</div>
<h3 class = "text-center mt-4 ">Articles</h3>    
<div class="flickr_pagination mb-4">
     <%= will_paginate @articles, :container => false %>
</div>
     <%=render 'articles/article'%>
     <div class="flickr_pagination mb-4">
<div class="page_info mb-2">
     <%= page_entries_info @articles %>
</div>
     <%= will_paginate @articles, :container => false %>      
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
    <div class="container text-center">
        <small>Copyright &copy; <%=link_to "TriForge Technology", "https://triforge.herokuapp.com/", clas: "text-white" %></small>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
    <%flash.each do |name, msg| %> 
             <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
        <%=msg%>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        </div> 
    <%end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
        <%= link_to 'TriBlog', root_path, clss:"navbar-brand", id: "logo" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%=link_to "Bloggers", users_path, class: "nav-link" %>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Articles
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%if logged_in?%>
                   <%=link_to "Create New Article", new_article_path, class: "dropdown-item"%>
                <%end%>
                <div class="dropdown-divider"></div>
                <%=link_to "View Articles", articles_path, class: "dropdown-item"%>
              </div>
            </li>
            
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Categories
              </a>
                 
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                 <%if logged_in? && current_user.admin?%>
                     <%=link_to "Create New Category", new_category_path, class: "dropdown-item"%>
                 <%end%>
                    <div class="dropdown-divider"></div>
                    <%=link_to "View Categories", categories_path, class: "dropdown-item"%>
              </div>
            </li>

            <%if logged_in? %>
             <li class="nav-item dropdown">
                 <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <%="Admin*"  if current_user.admin?%> Profile (=<%=current_user.username%>=)
                 </a>
               <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%=link_to "View your Profile! ", user_path(current_user), class: "dropdown-item"%>
                  <%=link_to "Edit Your Profile", edit_user_path(current_user), class: "dropdown-item"%>
                  <%= link_to "Delete your profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: {confirm: "Are you sure you want to do that?"}%>
               </div>
             </li>
              <li class="nav-item">
                 <%=link_to  "Log out", logout_path, class: "nav-link", method:  :delete %>
              </li> 

             <%else %>

               <li class="nav-item">
                 <%=link_to "Log In",login_path,class: "nav-link" %>
               </li>
               <li class="nav-item">
                 <%=link_to  "Signup", signup_path, class: "nav-link"%>
               </li> 
             <%end%>
          </ul>

          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Triblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
     <%=render 'layouts/navigation'%>
     <div id="page-content">
         <%= render 'layouts/messages' %>
         <%= yield %>
     </div>
     <%=render "layouts/footer"%>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Triforge!</h1>
<h2>Company mission statement</h2>
<p>
TriForge is committed to providing best in class IT services. 
Our mission is to use tried and tested industry methods, 
as well as some innovative methods to keep business big and small up and running.</p><br><br>

<h3>Company philosophy and vision</h3>
<p>
 Exceed our client’s expectations & Insist on the Highest Standards
 Develop long term relationships with our clients
 Revolutionize, Invent and Simplify present and future technologies
 Continuously improve our employees through training and education
 Continuously improve our processes and services
 Always act with integrity, honesty and professionalism
 Think Big, Think Logical, be Actionable
 Earn Trust of Others by Delivering Quality Results
Vision: TriForges vision is to build worldwide innovation & to connect businesses with customers in a seamless manner.
</p><br><br>

<%= link_to 'Home page', root_path%> 

app/views/pages/home.html.erb
<div id="page-content">
        <div class="container" id="home-container">
            <div class="jumbotron text-center text-white" >
                    <h1 class="display-4">Welcome To TriBlog!</h1>
                    <p class="lead">Where sharing your experiances and hobbies matters!</p>
                    <hr class="my-4">
                    <%= link_to "Sign Up!", signup_path, class: "btn btn-success btn-lg"  %>     
            </div>
             <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. A lacus vestibulum sed arcu non odio. Nullam eget felis eget nunc lobortis mattis aliquam faucibus purus. Faucibus ornare suspendisse sed nisi lacus. Faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis. Mattis enim ut tellus elementum sagittis. Dui faucibus in ornare quam viverra orci sagittis eu volutpat. Eget egestas purus viverra accumsan in nisl nisi scelerisque eu. Ante in nibh mauris cursus. Feugiat vivamus at augue eget arcu dictum varius duis at. Rhoncus urna neque viverra justo nec ultrices dui. Morbi non arcu risus quis varius quam quisque. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Consectetur adipiscing elit pellentesque habitant morbi tristique senectus et netus. Pretium fusce id velit ut tortor pretium viverra. Ante in nibh mauris cursus mattis molestie a. Mus mauris vitae ultricies leo integer malesuada nunc.</p>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. A lacus vestibulum sed arcu non odio. Nullam eget felis eget nunc lobortis mattis aliquam faucibus purus. Faucibus ornare suspendisse sed nisi lacus. Faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis. Mattis enim ut tellus elementum sagittis. Dui faucibus in ornare quam viverra orci sagittis eu volutpat. Eget egestas purus viverra accumsan in nisl nisi scelerisque eu. Ante in nibh mauris cursus. Feugiat vivamus at augue eget arcu dictum varius duis at. Rhoncus urna neque viverra justo nec ultrices dui. Morbi non arcu risus quis varius quam quisque. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Consectetur adipiscing elit pellentesque habitant morbi tristique senectus et netus. Pretium fusce id velit ut tortor pretium viverra. Ante in nibh mauris cursus mattis molestie a. Mus mauris vitae ultricies leo integer malesuada nunc.</p>
               <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. A lacus vestibulum sed arcu non odio. Nullam eget felis eget nunc lobortis mattis aliquam faucibus purus. Faucibus ornare suspendisse sed nisi lacus. Faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis. Mattis enim ut tellus elementum sagittis. Dui faucibus in ornare quam viverra orci sagittis eu volutpat. Eget egestas purus viverra accumsan in nisl nisi scelerisque eu. Ante in nibh mauris cursus. Feugiat vivamus at augue eget arcu dictum varius duis at. Rhoncus urna neque viverra justo nec ultrices dui. Morbi non arcu risus quis varius quam quisque. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Consectetur adipiscing elit pellentesque habitant morbi tristique senectus et netus. Pretium fusce id velit ut tortor pretium viverra. Ante in nibh mauris cursus mattis molestie a. Mus mauris vitae ultricies leo integer malesuada nunc.</p>
        </div>
 </div>

   
    <%# <%=link_to 'Articles', articles_path%> 
    <%# <%=link_to 'Create Article', new_article_path%>  
    <%# <%=link_to 'About', about_path%> 
   


    

app/views/users/edit.html.erb
 <h1 class = "text-center mt-5 font-weight-bold ">Edit Profile</h1>
        <%=render 'form'%>

app/views/users/index.html.erb
 <h1 class = "text-center mt-5 font-weight-bold ">TriBlogger`s</h1>
     <div class="flickr_pagination">
         <%= will_paginate @users, :container => false %>
      </div>      
       <div class="container">
                <% @users.each do |user|%>
                <div class="row justify-content-md-center">
                    <div class="col-8 mt-4">
                        <div class="card text-center shadow mb-5 bg-white rounded">
                        <div class="card-header font-italic">
                         <%= link_to user.username, user%>
                    </div>
                        <div class="card-body">
                            <h5 class="card-title"><%= link_to gravatar_for(user, size: 150), user %></td></h5>
                            <p class="card-text"><%= pluralize(user.articles.count, "article") %></td></p>
                            <%= link_to "View Profile", user, class: "btn btn-success"%>   
                            <%if logged_in?%>
                                <% if user == current_user%>
                                     <%= link_to "Edit", edit_user_path(user), class: "btn btn-warning" %>
                                <%end%>
                                <%if current_user.admin?%>
                                    <%= link_to "Delete User", user_path(user), class: "btn btn-danger", method: :delete,
                                       data: {confirm: "Are you sure you want to delete user and data?"}%>
                                   <%end%>
                            <%end%>

                        </div>
                        <div class="card-footer text-muted">
                             <small>Joined <%= time_ago_in_words(user.created_at) %> ago,</small> 
        
                        </div>
                </div>
        </div>
    </div>
    <%end%>
    </div>   
     <div class="flickr_pagination mb-4">
        <div class="page_info mb-2">
            <%= page_entries_info @users %>
        </div>
         <%= will_paginate @users, :container => false %>
      </div>

app/views/users/new.html.erb
 <h1 class = "text-center mt-5 font-weight-bold ">Sign up to TriBlog</h1>
        <%=render 'form'%>

app/views/users/show.html.erb
 <h1 class = "text-center mt-4  "><%=@user.username %>`s Profile!</h1>
       <%=  gravatar_for @user, size: 200%>
       <div class= "text-center mt-4">
       <%if logged_in? && @user == current_user %>
             <%= link_to "Edit your profile",edit_user_path(@user) ,class: "btn btn-warning" %>
       <%end%>
       </div>

<h3 class = "text-center mt-4 ">Articles</h3>    
       <div class="flickr_pagination mb-4">
             <%= will_paginate @articles, :container => false %>
       </div>

    <%=render 'articles/article'%>
       <div class="flickr_pagination mb-4">
             <div class="page_info mb-2">
                   <%= page_entries_info @articles %>
             </div>
             <%= will_paginate @articles, :container => false %>
       </div>